### ISSUE TITLE
Port from pandas to dask

### ISSUE THREAD

**Issue by Hsankesara** [RADAR-base/radar-pipeline#8]
Port all the current code to pandas dataframe to dask dataframe. The reason behind the porting is that dask is supposed to more efficient in handling large data, and it provides parallel processing.

**Comment by thepushkarp** [comment]
As per our previous meetings, we decided to use pySpark for data reading and its corresponding DataFrame module (instead of pandas) for representing data internally in the pipeline.

[This](https://censius.ai/blogs/apache-spark-vs-dask-vs-pandas) and [this](https://medium.datadriveninvestor.com/pandas-dask-or-pyspark-what-should-you-choose-for-your-dataset-c0f67e1b1d36) are two that articles make a detailed comparison of pandas, dask and pyspark. Since pySpark has similar lazy data loading and parallel processing capability for large data as dask, I think we skip using dask in the pipeline.

**Comment by Hsankesara** [comment]
Yeah, I think pySpark would be much more efficient that dask for reading the big data.
